id = "helm"
name = "Helm"
description = "Syntax highlighting for Helm templates."
version = "0.0.2"
schema_version = 1
authors = ["Hemant Joshi <mail@hjoshi.me>", "Christian Lee Seibold <christian.seibold32@outlook.com>"]
repository = "https://github.com/clseibold/helm.zed"

[grammars.helm]
repository = "https://github.com/ngalaiko/tree-sitter-go-template"
commit = "fe6bb984fe4f0b1661b24ff613be5163f33b2a19"
